//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public int t_id { get; set; }
        public string nameOnCard { get; set; }
        public string cardNumber { get; set; }
        public decimal unit_price { get; set; }
        public int quantity { get; set; }
        public decimal total_price { get; set; }
        public string exp_Date { get; set; }
        public System.DateTime createdOn { get; set; }
        public string createdBy { get; set; }
        public int c_id { get; set; }
        public int s_id { get; set; }
        public int user_id { get; set; }
    
        public virtual creditcard_type creditcard_type { get; set; }
        public virtual schedule schedule { get; set; }
        public virtual user user { get; set; }
    }
}
