//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusBooking
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class transaction
    {
        public int t_id { get; set; }

        [Required(ErrorMessage = "Please enter the name on card")]
        public string nameOnCard { get; set; }

        [Required(ErrorMessage = "Please enter the Card Number")]
        [StringLength(16, MinimumLength = 15, ErrorMessage = "Invalid Card Number")]
        [RegularExpression(@"^[0-9]*$", ErrorMessage = "Only Digits")]
        public string cardNumber { get; set; }

        public decimal unit_price { get; set; }
        public int quantity { get; set; }
        public decimal total_price { get; set; }

        [Required(ErrorMessage = "Please enter the expiry date")]
        [RegularExpression(@"0[1-9]|10|11|12)/202[0 - 9]{1}$", ErrorMessage = "Invalid Expiry date")]
        public string exp_Date { get; set; }

        public System.DateTime createdOn { get; set; } = DateTime.Now;

        public string createdBy { get; set; }
        public int c_id { get; set; }
        public int s_id { get; set; }
        public int user_id { get; set; }

        public virtual creditcard_type creditcard_type { get; set; }
        public virtual schedule schedule { get; set; }
        public virtual user user { get; set; }
    }
}
